# Generated by Django 6.0.1 on 2026-02-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmatch',
            name='status',
            field=models.CharField(choices=[('NEW', 'New Match'), ('APPLIED', 'Applied'), ('INTERVIEW', 'Interviewing'), ('OFFER', 'Offer Received'), ('REJECTED', 'Rejected')], default='NEW', max_length=20),
        ),
    ]
